### ISSUE TITLE
Please grade hw # 4

### ISSUE THREAD

**Issue by ThuraDwe** [ThuraDwe/astr-119#9]
Also, how do I create a branch without it being the same as the main branch but its own separate branch with new files?

@ryarza @tangyao1123 

One more thing I can only see Yao's name for my assignees and I can't find Ricardo's name on there, help?

**Comment by ryarza** [comment]
Graded!

You could create a new branch and then delete the files you don't want. Also I don't have to be an assignee to grade the HW so no worries!
